require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "log/**/*"
    - "bin/**/*"
    - ".git/**/*"
    - "tmp/**/*"
    - "public/**/*"
    - 'node_modules/**/*'
    - "lib/templates/**/*"
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.7

Rails:
  Enabled: true

# Checks for proper usage of fail and raise.
Style/SignalException:
  Enabled: false

# Prefer ' strings when you don't need string interpolation or special symbols.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# 引数の数は5以上で警告とする
Metrics/ParameterLists:
  Max: 5

# メソッドの複雑さはチェックしない
Metrics/PerceivedComplexity:
  Enabled: false

# AbcSizeはチェックしない
Metrics/AbcSize:
  Enabled: false

# frozen_string_literal：trueは書かない
Style/FrozenStringLiteralComment:
  Enabled: false

# シンボルの配列の書き方の指定 :%iは使わない
Style/SymbolArray:
  Enabled: false

# Module名::Class名の書き方の指定なし
Style/ClassAndModuleChildren:
  Enabled: false

# 英語以外の文字があることを許可
Style/AsciiComments:
  Enabled: false

# Gemはアルファベット順に並べなくていい
Bundler/OrderedGems:
  Enabled: false

# ModuleやClassのドキュメントを書かなくてもいい
Style/Documentation:
  Enabled: false

# do~endが空であることを今はSpecファイルだけ許可
Lint/EmptyBlock:
  Exclude:
    - "spec/**/*"

# 1行長さに指定なし
Layout/LineLength:
  Enabled: false

# Block内の行数指定
Metrics/BlockLength:
  Exclude:
    - "lib/tasks/**/*"
    - "config/routes.rb"
    - "config/environments/**"

# if/unless分を1行で書かなくてもいい
Style/IfUnlessModifier:
  Enabled: false

# InverseOfは書かなくてもいい
Rails/InverseOf:
  Enabled: false

# メソッド名は17文字まで
Metrics/MethodLength:
  Max: 17

# 循環複雑度は8がMax
Metrics/CyclomaticComplexity:
  Max: 8

Rails/FilePath:
  Enabled: true