- id: 1
  range: 〜1万
- id: 2
  range: 1万〜3万
- id: 3
  range: 3万〜5万
- id: 4
  range: 5万〜10万
- id: 5
  range: 11万〜30万
- id: 6
  range: 31万〜50万
- id: 7
  range: 51万〜100万
- id: 8
  range: 101万〜300万
- id: 9
  range: 301万〜500万
- id: 10
  range: 501万〜